project_name: AppName
scoop:
  name: AppName
  commit_msg_template: Auto Update for {{ .ProjectName }} version {{ .Tag }}
  homepage: https://github.com/iiiusky/AppName
release:
  prerelease: auto
  name_template: "v{{.Version}}"
before:
  hooks:
    - go mod tidy
builds:
  - id: AppName
    env:
      - CGO_ENABLED=1
      - GO111MODULE=on
      - GOFLAGS=-trimpath
    goos:
      - darwin
    goarch:
      - amd64
    targets:
      - "darwin_amd64"
checksum:
  name_template: "{{ .ProjectName }}_darwin_amd64.sha256"
  algorithm: sha256
archives:
  - format: binary
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
